- name: Copy
  uses: andstor/copycat-action@v3
  with:
    personal_token: ${{ secrets.API_TOKEN_GITHUB }}
    src_path: /.
    dst_path: /_data/
    dst_owner: clintjb
    dst_repo_name: clintjb/clintjb.github.io
